### ISSUE TITLE
[FEATURE REQUEST] Disable "Select User" upon NRO forwarder startup

### ISSUE THREAD

**Issue by VirusBurst** [rlaphoenix/nton#19]
TL:DR; As it's written as title name ^^

Why? MultiUser Switch with too many NRO forwarder and just too lazy to select default user :P

**Comment by rlaphoenix** [comment]
Makes total sense since save data allocation is forced off. Therefore, all users start the forwarder ROM the exact same flow. This should be possible by editing the NACP file at offset 0x3025 from 0x01 to 0x00. Though, that hasn't been tried and may not work like I think.

I'll give this a shot very soon and let you know.

**Comment by rlaphoenix** [comment]
The idea I had worked like a charm on my System with 2x users. :) Thanks for the suggestion.
