### ISSUE TITLE
Portable version not running

### ISSUE THREAD

**Issue by Woozellin** [rlaphoenix/nton#21]
Hi, really like the idea of this app! 

However, I just tried the NTON-v2.0.0-portable.exe and it is not running for me. 
I'm using Windows 11
Version 22H2 Build 22621.2134

When I double click the NTON portable.exe version, I get the 'thinking' hourglass for about 1 second, then nothing, no errors, no crashes. I looked in Task Manager, NTON is not there. 

I believe I'm fully updated but let me know if there is any logs I can check or anything. 

I have not tried the Setup install yet.  I kind of don't want to, I'd rather just run the simple portable version. 

Thanks! Please let me know if you'd like me to test anything!

**Comment by rlaphoenix** [comment]
Hi, could you try the Installer version and see if that one will launch? It's not immediately clear why the portable version is failing to launch, nor ways to debug since it's a GUI application.

You could still perhaps try launch the exe from PowerShell or CMD and see if that gives any information. When it works, it should give no response text at all and simply launch.

Another option is to build a custom portable build with the console window kept active to see if any error information gets sent there.

**Comment by lborruto** [comment]
Same for me, installer or portable version.

**Comment by rlaphoenix** [comment]
> Same for me, installer or portable version.

I can only assume more weirdness with PyInstaller then. Have you tried anything I told the original issue creator?

**Comment by lborruto** [comment]
> 

So after doing `$ pip install nton[gui]` the installer or portable file works fine!

**Comment by rlaphoenix** [comment]
I've managed to recreate the bug by just opening a new Windows Sandbox environment and downloading the portable version. Since @lborruto got it working by installing the dependencies outside the portable/setup version, it's likely that there's some dependency that PyInstaller did not handle. Looking into it now.

**Comment by rlaphoenix** [comment]
I've already noticed one possible problem. If you don't have one of the dependencies that are required, i.e. the bundled binaries like hacbrew, or the prod.keys, then it will just print a message and exit. Since the console window is removed on the GUI you never get to see these messages. So that could be one cause.

**Comment by lborruto** [comment]
> I've already noticed one possible problem. If you don't have one of the dependencies that are required, i.e. the bundled binaries like hacbrew, or the prod.keys, then it will just print a message and exit. Since the console window is removed on the GUI you never get to see these messages. So that could be one cause.
> 
> On my Windows Sandbox where I reproduced the error, simply putting the prod.keys file next to the portable exe, or in the %userprofile%/.switch folder, made the GUI actually open. It's likely this is the case for you guys as well.
> 
> However, with @lborruto saying installing via pip fixed it for him, is very strange.

I think you are right, I've added prokeys to `C:\Users\<User>\.switch\` AND installed with pip.

**Comment by rlaphoenix** [comment]
> > I've already noticed one possible problem. If you don't have one of the dependencies that are required, i.e. the bundled binaries like hacbrew, or the prod.keys, then it will just print a message and exit. Since the console window is removed on the GUI you never get to see these messages. So that could be one cause.
> > On my Windows Sandbox where I reproduced the error, simply putting the prod.keys file next to the portable exe, or in the %userprofile%/.switch folder, made the GUI actually open. It's likely this is the case for you guys as well.
> > However, with @lborruto saying installing via pip fixed it for him, is very strange.
> 
> I think you are right, I've added prokeys to `C:\Users\<User>\.switch\` AND installed with pip.

Ahh, as in you did both and THEN noticed it started working? If that's the case then the solution has been found, I just need to add a GUI message box when the prod.keys and other dependencies are not found :)

**Comment by rlaphoenix** [comment]
Considered fixed as of https://github.com/rlaphoenix/nton/commit/c7fff1fd5ce453dbf14e02aa8d4e786443e7f837

If it's still happening please make a new issue.
