### ISSUE TITLE
Build fails for DBI forwarder 

### ISSUE THREAD

**Issue by Skywalker25** [rlaphoenix/nton#4]
**Describe the bug**
nstool fails to extract the ncap from a NRO and exits the process (DBI.nro)

**To Reproduce**

1. PIP Install nton
2. run cmd nton build --sdmc "/switch/DBI.nro" PATH/TO/NRO/DBI.nro
3. program exits while trying to extract the ncap from nro. 

**Expected behavior**

Ideally the program should skip the extract and create a new ncap but it seems it's an issue with nstool and not nton. 
A new cmd option should be added to skip the extract and create a new control.ncap for those troublesome nros. 

**Screenshots**
![Screenshot_20221118_060601](https://user-images.githubusercontent.com/17167674/202822930-e8d3e229-71c5-42a6-9e71-89f507326333.png)

**Additional context**

**Comment by rlaphoenix** [comment]
Well I can see it's actually failing at the nstool verification call, not specifically the extraction call. However, it is also failing at that. We should probably make this issue on nstool.

**Comment by rlaphoenix** [comment]
I've added in master two new CLI flags, `--no-verify` and `--craft-nacp`. `--no-verify` will skip verification and `--craft-nacp` will create a new nacp instead of trying to extract one. There's already `--icon` for putting a manual icon in case of icon extraction failure, so no need for anything new there.

I'm considering these temporary/last-resort flags though and might not keep them. I might not even bring them to a new stable release, I will see what the nstool guy says in the Issue, https://github.com/jakcron/nstool/issues/86 and if a proper solution can be ironed out I might just remove these arguments.

This project's main goal is to be safety-first. Having flags like these is just bad practice. However, I understand that right now without these flags there's no way to make forwarders for at least one NRO (probably more).

**Comment by rlaphoenix** [comment]
jakcron seems to indicate that it's a relatively simple fix, therefore I likely won't be pushing these flags to a stable release. I will keep them in master for now until a fix is out, at which those commits will be deleted and the fixed stable or pre-release will be advised to be used.

**Comment by rlaphoenix** [comment]
I've moved those new flags to `nstool-workarounds` branch.

**Comment by jakcron** [comment]
Please try with [NSTool 1.6.6](https://github.com/jakcron/nstool/releases/tag/v1.6.6)

**Comment by rlaphoenix** [comment]
Fixed if you use nstool v1.6.6
